name: online_groceries
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fl_country_code_picker: ^0.1.5
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  flutter_timezone: ^4.1.1
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.3
  flutter_datetime_picker_plus: ^2.1.0
  image_picker: ^1.1.1
  win32: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/app_logo_design.png"

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/font/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/font/Gilroy-Regular.ttf
        - asset: assets/font/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/font/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/font/Gilroy-Bold.ttf
          weight: 700
    - family: Airbnb Cereald
      fonts:
        - asset: assets/font/Airbnb-Cereald-Medium.otf
    - family: Sveningsson
      fonts:
        - asset: assets/font/Sveningsson.ttf
